[build]
phases = [
    { name = "install", commands = ["npm ci --python=python3"] },
    { name = "build", commands = ["npm run build"] },
]

[start]
commands = ["npm start"]

[dependencies]
apt = ["python3", "python3-dev", "make", "g++"]
