[build]
phases = [
    { name = "install", commands = ["npm config set python /usr/bin/python3", "npm ci --python=python3"] },
    { name = "build", commands = ["npm run build"] },
]

[start]
commands = ["npm start"]

[dependencies]
apt = ["python3", "python3-dev", "make", "g++"]

[environment]
PYTHON = "/usr/bin/python3"
